package com.trabalho.dfmapa04102020;

/**
 *
 * @author Daniel F
 */
public class PainelFrame extends javax.swing.JFrame {

    private Painel painel;

    /**
     * Creates new form PainelFrame
     */
    public PainelFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTopo = new javax.swing.JPanel();
        lbProximaSenha = new javax.swing.JLabel();
        lbProximoCaixa = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        pnClientes = new javax.swing.JPanel();
        lbEscolhaTipoAtendimento = new javax.swing.JLabel();
        btnComum = new javax.swing.JButton();
        btnRapido = new javax.swing.JButton();
        btnPrioritario = new javax.swing.JButton();
        lbSuaSenha = new javax.swing.JLabel();
        txtSuaSenha = new javax.swing.JTextField();
        pnCaixas = new javax.swing.JPanel();
        btnCaixa1 = new javax.swing.JButton();
        btnCaixa2 = new javax.swing.JButton();
        btnCaixa3 = new javax.swing.JButton();
        btnCaixa4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Painel de Atendimento");

        lbProximaSenha.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        lbProximaSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbProximaSenha.setText("Próxima Senha");

        lbProximoCaixa.setFont(new java.awt.Font("Ubuntu", 2, 36)); // NOI18N
        lbProximoCaixa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbProximoCaixa.setText("Próximo Caixa");

        jInternalFrame1.setVisible(false);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(21, Short.MAX_VALUE)))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout pnTopoLayout = new javax.swing.GroupLayout(pnTopo);
        pnTopo.setLayout(pnTopoLayout);
        pnTopoLayout.setHorizontalGroup(
            pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTopoLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(lbProximaSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                .addGap(93, 93, 93)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTopoLayout.createSequentialGroup()
                    .addContainerGap(58, Short.MAX_VALUE)
                    .addComponent(lbProximoCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(38, 38, 38)))
        );
        pnTopoLayout.setVerticalGroup(
            pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTopoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbProximaSenha)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnTopoLayout.createSequentialGroup()
                    .addGap(97, 97, 97)
                    .addComponent(lbProximoCaixa)
                    .addContainerGap(134, Short.MAX_VALUE)))
        );

        pnClientes.setBorder(javax.swing.BorderFactory.createTitledBorder("Para clientes"));
        pnClientes.setName("pnClientes"); // NOI18N
        pnClientes.setPreferredSize(new java.awt.Dimension(258, 178));

        lbEscolhaTipoAtendimento.setText("Escolha seu tipo de atendimento");

        btnComum.setText("Comum");
        btnComum.setName("btnComum"); // NOI18N
        btnComum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComumActionPerformed(evt);
            }
        });

        btnRapido.setText("Rápido");
        btnRapido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRapidoActionPerformed(evt);
            }
        });

        btnPrioritario.setText("Preferencial");
        btnPrioritario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrioritarioActionPerformed(evt);
            }
        });

        lbSuaSenha.setLabelFor(txtSuaSenha);
        lbSuaSenha.setText("Sua senha é:");

        txtSuaSenha.setEditable(false);
        txtSuaSenha.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        txtSuaSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout pnClientesLayout = new javax.swing.GroupLayout(pnClientes);
        pnClientes.setLayout(pnClientesLayout);
        pnClientesLayout.setHorizontalGroup(
            pnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSuaSenha)
                    .addGroup(pnClientesLayout.createSequentialGroup()
                        .addGroup(pnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbEscolhaTipoAtendimento)
                            .addComponent(lbSuaSenha))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnClientesLayout.createSequentialGroup()
                        .addComponent(btnComum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(btnRapido)
                        .addGap(53, 53, 53)
                        .addComponent(btnPrioritario)))
                .addContainerGap())
        );
        pnClientesLayout.setVerticalGroup(
            pnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnClientesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbEscolhaTipoAtendimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(pnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRapido)
                    .addComponent(btnComum)
                    .addComponent(btnPrioritario))
                .addGap(14, 14, 14)
                .addComponent(lbSuaSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSuaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        pnCaixas.setBorder(javax.swing.BorderFactory.createTitledBorder("Para caixas"));
        pnCaixas.setPreferredSize(new java.awt.Dimension(258, 178));

        btnCaixa1.setText("Caixa 1");
        btnCaixa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaixa1ActionPerformed(evt);
            }
        });

        btnCaixa2.setText("Caixa 2");
        btnCaixa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaixa2ActionPerformed(evt);
            }
        });

        btnCaixa3.setText("Caixa 3");
        btnCaixa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaixa3ActionPerformed(evt);
            }
        });

        btnCaixa4.setText("Caixa 4");
        btnCaixa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaixa4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnCaixasLayout = new javax.swing.GroupLayout(pnCaixas);
        pnCaixas.setLayout(pnCaixasLayout);
        pnCaixasLayout.setHorizontalGroup(
            pnCaixasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCaixasLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnCaixasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCaixa1)
                    .addComponent(btnCaixa3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addGroup(pnCaixasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCaixa2)
                    .addComponent(btnCaixa4))
                .addGap(33, 33, 33))
        );
        pnCaixasLayout.setVerticalGroup(
            pnCaixasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCaixasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCaixasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCaixa1)
                    .addComponent(btnCaixa2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(pnCaixasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCaixa3)
                    .addComponent(btnCaixa4))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnCaixas, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnTopo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(pnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(396, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnTopo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnCaixas, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(300, Short.MAX_VALUE)
                    .addComponent(pnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrioritarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrioritarioActionPerformed
        Senha senhaGerada = this.getPainel().adicionarSenhaNaFila('P');
        txtSuaSenha.setText(senhaGerada.getSenhaTxt());
        this.printTodasAsSenhas();
    }//GEN-LAST:event_btnPrioritarioActionPerformed

    private void btnComumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComumActionPerformed
        Senha senhaGerada = this.getPainel().adicionarSenhaNaFila('C');
        txtSuaSenha.setText(senhaGerada.getSenhaTxt());
        this.printTodasAsSenhas();
    }//GEN-LAST:event_btnComumActionPerformed

    private void btnRapidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRapidoActionPerformed
        Senha senhaGerada = this.getPainel().adicionarSenhaNaFila('R');
        txtSuaSenha.setText(senhaGerada.getSenhaTxt());
        this.printTodasAsSenhas();
    }//GEN-LAST:event_btnRapidoActionPerformed


    private void btnCaixa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixa1ActionPerformed
        String atendimento = this.getPainel().atender('P');
        if (atendimento != null) {
            this.lbProximoCaixa.setText("Caixa 1");
            this.lbProximaSenha.setText(atendimento);
        }
        this.printTodasAsSenhas();
    }//GEN-LAST:event_btnCaixa1ActionPerformed

    private void btnCaixa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixa2ActionPerformed
        String atendimento = this.getPainel().atender('R');
        if (atendimento != null) {
            this.lbProximoCaixa.setText("Caixa 2");
            this.lbProximaSenha.setText(atendimento);
        }
        this.printTodasAsSenhas();
    }//GEN-LAST:event_btnCaixa2ActionPerformed

    private void btnCaixa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixa3ActionPerformed
        String atendimento = this.getPainel().atender('R');
        if (atendimento != null) {
            this.lbProximoCaixa.setText("Caixa 3");
            this.lbProximaSenha.setText(atendimento);
        }
        this.printTodasAsSenhas();
    }//GEN-LAST:event_btnCaixa3ActionPerformed

    private void btnCaixa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixa4ActionPerformed
        String atendimento = this.getPainel().atender('C');
        if (atendimento != null) {
            this.lbProximoCaixa.setText("Caixa 4");
            this.lbProximaSenha.setText(atendimento);
        }
        this.printTodasAsSenhas();
    }//GEN-LAST:event_btnCaixa4ActionPerformed

    private void printTodasAsSenhas() {
        this.jTextArea1.setText("");
        for (Senha senha : this.getPainel().getFila()) {
            this.jTextArea1.append(senha.getSenhaTxt() + '\r' + '\n');
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PainelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PainelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PainelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PainelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PainelFrame().setVisible(true);
            }
        });
    }

    public Painel getPainel() {
        if (this.painel == null) {
            this.painel = new Painel();
        }
        return painel;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaixa1;
    private javax.swing.JButton btnCaixa2;
    private javax.swing.JButton btnCaixa3;
    private javax.swing.JButton btnCaixa4;
    private javax.swing.JButton btnComum;
    private javax.swing.JButton btnPrioritario;
    private javax.swing.JButton btnRapido;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbEscolhaTipoAtendimento;
    private javax.swing.JLabel lbProximaSenha;
    private javax.swing.JLabel lbProximoCaixa;
    private javax.swing.JLabel lbSuaSenha;
    private javax.swing.JPanel pnCaixas;
    private javax.swing.JPanel pnClientes;
    private javax.swing.JPanel pnTopo;
    private javax.swing.JTextField txtSuaSenha;
    // End of variables declaration//GEN-END:variables
}
