package com.trabalho.dfmapa04102020;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel F
 */
public class PainelFrame extends javax.swing.JFrame {

    private List<Senha> fila = new ArrayList<Senha>();
    
    /**
     * Creates new form PainelFrame
     */
    public PainelFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbProximaSenha = new javax.swing.JLabel();
        lbProximoCaixa = new javax.swing.JLabel();
        pnClientes = new javax.swing.JPanel();
        lbEscolhaTipoAtendimento = new javax.swing.JLabel();
        btnComum = new javax.swing.JButton();
        btnRapido = new javax.swing.JButton();
        btnPrioritario = new javax.swing.JButton();
        lbSuaSenha = new javax.swing.JLabel();
        txtSuaSenha = new javax.swing.JTextField();
        pnCaixas = new javax.swing.JPanel();
        btnCaixa1 = new javax.swing.JButton();
        btnCaixa2 = new javax.swing.JButton();
        btnCaixa3 = new javax.swing.JButton();
        btnCaixa4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Painel de Atendimento");

        lbProximaSenha.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        lbProximaSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbProximaSenha.setText("P-5");

        lbProximoCaixa.setFont(new java.awt.Font("Ubuntu", 2, 36)); // NOI18N
        lbProximoCaixa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbProximoCaixa.setText("Caixa 1");

        pnClientes.setBorder(javax.swing.BorderFactory.createTitledBorder("Para clientes"));
        pnClientes.setName("pnClientes"); // NOI18N
        pnClientes.setPreferredSize(new java.awt.Dimension(258, 178));

        lbEscolhaTipoAtendimento.setText("Escolha seu tipo de atendimento");

        btnComum.setText("Comum");
        btnComum.setName("btnComum"); // NOI18N
        btnComum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComumActionPerformed(evt);
            }
        });

        btnRapido.setText("Rápido");

        btnPrioritario.setText("Prioritário");
        btnPrioritario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrioritarioActionPerformed(evt);
            }
        });

        lbSuaSenha.setLabelFor(txtSuaSenha);
        lbSuaSenha.setText("Sua senha é:");

        txtSuaSenha.setEditable(false);
        txtSuaSenha.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        txtSuaSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSuaSenha.setText("P-6");

        javax.swing.GroupLayout pnClientesLayout = new javax.swing.GroupLayout(pnClientes);
        pnClientes.setLayout(pnClientesLayout);
        pnClientesLayout.setHorizontalGroup(
            pnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSuaSenha)
                    .addGroup(pnClientesLayout.createSequentialGroup()
                        .addGroup(pnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbEscolhaTipoAtendimento)
                            .addComponent(lbSuaSenha))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnClientesLayout.createSequentialGroup()
                        .addComponent(btnComum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(btnRapido)
                        .addGap(53, 53, 53)
                        .addComponent(btnPrioritario)))
                .addContainerGap())
        );
        pnClientesLayout.setVerticalGroup(
            pnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnClientesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbEscolhaTipoAtendimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(pnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRapido)
                    .addComponent(btnComum)
                    .addComponent(btnPrioritario))
                .addGap(14, 14, 14)
                .addComponent(lbSuaSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSuaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        pnCaixas.setBorder(javax.swing.BorderFactory.createTitledBorder("Para caixas"));
        pnCaixas.setPreferredSize(new java.awt.Dimension(258, 178));

        btnCaixa1.setText("Caixa 1");

        btnCaixa2.setText("Caixa 2");
        btnCaixa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaixa2ActionPerformed(evt);
            }
        });

        btnCaixa3.setText("Caixa 3");

        btnCaixa4.setText("Caixa 4");
        btnCaixa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaixa4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnCaixasLayout = new javax.swing.GroupLayout(pnCaixas);
        pnCaixas.setLayout(pnCaixasLayout);
        pnCaixasLayout.setHorizontalGroup(
            pnCaixasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCaixasLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnCaixasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCaixa1)
                    .addComponent(btnCaixa3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addGroup(pnCaixasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCaixa2)
                    .addComponent(btnCaixa4))
                .addGap(33, 33, 33))
        );
        pnCaixasLayout.setVerticalGroup(
            pnCaixasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCaixasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCaixasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCaixa1)
                    .addComponent(btnCaixa2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(pnCaixasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCaixa3)
                    .addComponent(btnCaixa4))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbProximaSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbProximoCaixa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnCaixas, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(pnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(384, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbProximaSenha)
                .addGap(37, 37, 37)
                .addComponent(lbProximoCaixa)
                .addGap(35, 35, 35)
                .addComponent(pnCaixas, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(198, 198, 198)
                    .addComponent(pnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrioritarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrioritarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrioritarioActionPerformed

    private void btnCaixa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCaixa2ActionPerformed

    private void btnCaixa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixa4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCaixa4ActionPerformed

    private void btnComumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComumActionPerformed
        Senha senhaComum = new Senha(1, 'C');
        this.getFila().add(senhaComum);
        JOptionPane.showMessageDialog(this, "Na fila: " + this.getFila().size());
    }//GEN-LAST:event_btnComumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PainelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PainelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PainelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PainelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

               
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PainelFrame painelFrame = new PainelFrame();
                painelFrame.setFila(new ArrayList<Senha>());
                painelFrame.setVisible(true);
            }
        });
    }

    public List<Senha> getFila() {
        return fila;
    }

    public void setFila(List<Senha> fila) {
        this.fila = fila;
    }
    
    
    
    
    private void adicionarSenhaNaFila(Senha senha) {
        this.getFila().add(senha);
    }
    
    private void atender(int caixa) {
        
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaixa1;
    private javax.swing.JButton btnCaixa2;
    private javax.swing.JButton btnCaixa3;
    private javax.swing.JButton btnCaixa4;
    private javax.swing.JButton btnComum;
    private javax.swing.JButton btnPrioritario;
    private javax.swing.JButton btnRapido;
    private javax.swing.JLabel lbEscolhaTipoAtendimento;
    private javax.swing.JLabel lbProximaSenha;
    private javax.swing.JLabel lbProximoCaixa;
    private javax.swing.JLabel lbSuaSenha;
    private javax.swing.JPanel pnCaixas;
    private javax.swing.JPanel pnClientes;
    private javax.swing.JTextField txtSuaSenha;
    // End of variables declaration//GEN-END:variables
}
